### ISSUE TITLE
Python3 port

### ISSUE THREAD

**Issue by dglava** [baverman/orcsome#11]
What's the likelihood of Orcsome getting a Python3 port?

Orcsome is one of those programs that just work and have been running for years. I've just noticed that it's the only Python 2 package left on my computer. There's a "Python3 Port" in the TODO's in the README.

**Comment by baverman** [comment]
Extremely likely :)) I use and going to use Orcsome myself. I have a plan to get a vacation to move all my projects to py3 till the end of this year.

**Comment by QiangF** [comment]
There is already a py3 port
https://github.com/nlfiasel/orcsome-desktop-snapshot

**Comment by dglava** [comment]
I just quickly tested the latest build from master and it's working great. Thanks!
I guess this issue can be closed? The README can also probably be updated (Python3 related TODO) :smiley: ?

**Comment by baverman** [comment]
Thank you for early test! I wanted to catch all bugs by myself. And it seems stable enough. I'm going to make proper release next week.

And thank you for pushing me, it's a great feel to drop python2.

**Comment by butyoutried** [comment]
Python3 port is here, great. Waiting for the release, particularly in AUR :)
