### ISSUE TITLE
spawn_or_raise race condition 

### ISSUE THREAD

**Issue by paul-axe** [baverman/orcsome#3]
seems like there is race condition in spawn_or_raise func. In my configuration change_window_desktop results after focus_and_raise function. So with bring_to_current arg we changing current desktop to client's desktop and then move client to desktop we've been before. When i added sleep between this calls all worked fine, but it's not a good solution ;)

**Comment by baverman** [comment]
Yes, X window is an async system and where may be some weird situations. What wm do you use? I can add sleep param as quick and dirty workaround.

**Comment by paul-axe** [comment]
I'm testing in openbox. Sleep is not the thing that should appear in official repo i think, so i can add sleep myself in my copy until nice solution released

**Comment by baverman** [comment]
Can you post <focus> section from rc.xml? Mine is
```
<focus>
  <focusNew>yes</focusNew>
  <!-- always try to focus new windows when they appear. other rules do
       apply -->
  <followMouse>no</followMouse>
  <!-- move focus to a window when you move the mouse into it -->
  <focusLast>yes</focusLast>
  <!-- focus the last used window when changing desktops, instead of the one
       under the mouse pointer. when followMouse is enabled -->
  <underMouse>no</underMouse>
  <!-- move focus under the mouse, even when the mouse is not moving -->
  <focusDelay>200</focusDelay>
  <!-- when followMouse is enabled, the mouse must be inside the window for
       this many milliseconds (1000 = 1 sec) before moving focus to it -->
  <raiseOnFocus>no</raiseOnFocus>
  <!-- when followMouse is enabled, and a window is given focus by moving the
       mouse into it, also raise the window -->
</focus>
```

**Comment by paul-axe** [comment]
My <focus> section is same (i think it default config part)

**Comment by baverman** [comment]
I'll reread NETWM spec carefully, seems I violate some protocol.

**Comment by paul-axe** [comment]
I analyzed wmctrl source code as an example of NETWM usage, and there is no difference between it's logic and orcsome. Seems like it should use callback or something to avoid races.

**Comment by baverman** [comment]
There is the only missing thing: orcsome can provide a timestamp to X server. Now it behaves like an old client.

**Comment by baverman** [comment]
> Seems like it should use callback or something to avoid races.

Listen to active window property change? And we should do timeout for this event. Looks good.

**Comment by paul-axe** [comment]
Can't find in documentation, what is timestamp field using for?

**Comment by baverman** [comment]
It's additional field that let WM to serialize requests from multiple clients.http://standards.freedesktop.org/wm-spec/wm-spec-1.3.html#idm140130317679168

**Comment by paul-axe** [comment]
I tried to do it with callback, but no success. There is strange behavior with desktop blinking (because of fast switching i guess). The code is:

```
        if client:
            if bring_to_current:
                @self.on_property_change(client, '_NET_WM_DESKTOP')
                def focus_and_raise_cb():
                    self.focus_and_raise(client)
                self.change_window_desktop(client, self.current_desktop)
            else:
                self.focus_and_raise(client)
```

**Comment by baverman** [comment]
I think there is some openbox intervention here. It tries to switch desktop themself.

**Comment by paul-axe** [comment]
Then why it working correct after sleep added? I think it not because of
openbox
28 окт. 2015 г. 16:36 пользователь "Anton Bobrov" <notifications@github.com>
написал:

**Comment by baverman** [comment]
I don't blame openbox. May be you have another software. Sleep lets orcosme do the job at last place.

**Comment by paul-axe** [comment]
I tested on xfwm4 and there is another behavior. WM just goes to client's desktop, without moving it to current. Seems like it moving focus to window first (and activating clients desktop), then trying move it to current desktop (which actually is client's original desktop now).

**Comment by paul-axe** [comment]
Oh damn, i looked at my source code in this thread and realized that i forget to delete cb handler. Now it works nice. I need some more time for testing and then i'll made pull request

**Comment by baverman** [comment]
It's funny but this fix broke my rc.py) And I don't know the cause. Seems things more complicated.

**Comment by baverman** [comment]
It's an old bug with race in my rc.py))
