### ISSUE TITLE
Problems getting it to run — permission error cffi

### ISSUE THREAD

**Issue by dglava** [baverman/orcsome#9]
I am getting a permission error when I try to run Orcsome.

```
Traceback (most recent call last):
  File "/usr/bin/orcsome", line 3, in <module>
    from orcsome.run import run
  File "/usr/lib/python2.7/site-packages/orcsome/run.py", line 7, in <module>
    from . import VERSION, ev
  File "/usr/lib/python2.7/site-packages/orcsome/ev.py", line 44, in <module>
    """, libraries=['ev'])
  File "/usr/lib/python2.7/site-packages/cffi/api.py", line 437, in verify
    lib = self.verifier.load_library()
  File "/usr/lib/python2.7/site-packages/cffi/verifier.py", line 112, in load_library
    self._write_source()
  File "/usr/lib/python2.7/site-packages/cffi/verifier.py", line 201, in _write_source
    with open(self.sourcefilename, "w") as fp:
IOError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/orcsome/__pycache__/_cffi__x3e7c5c56x108dc361.c'
```
The permissions of the file are:
`-rw-r--r-- 1 root root 84055 Feb 27 18:59 _cffi__x703cd531x78635c57.c`.
I changed them to 666, but I still received the error.

Am I doing something wrong?

**Comment by baverman** [comment]
This is very interesting. cffi tries to build module on the fly. Which version of cffi do you have?

**Comment by baverman** [comment]
Yep, bug confirmed. I never install orcsome as system wide package) For workaround you can build extensions under your user and install as root:

```
sudo rm -rf /usr/lib/python2.7/site-packages/orcsome*
python2 -m pip install -e git+https://github.com/baverman/orcsome.git#egg=orcsome
sudo python2 -m pip install -e git+https://github.com/baverman/orcsome.git#egg=orcsome
```

First pip clones and builds package into $HOME/.src and exits with an error and it is normal. Second pip install link into system site-packages.

**Comment by dglava** [comment]
Thanks for the quick reply.
My version of python-cffi is 1.9.1.

Since I don't like using pip, I used the --user flag with the setup.py file (packaged into a proper package for Arch Linux).

Do you have plans on fixing this, i.e.: making it possible to install Orcsome system wide?

**Comment by baverman** [comment]
Yes, I'm preparing fix now. I think it will be ready in two hours. And I upload package to PyPi finally)

**Comment by baverman** [comment]
Fixed. Also I have updated AUR package.

**Comment by dglava** [comment]
Thanks!
